export const activities = [
    "Select Category",
    "Hiking & Trekking",
    "Camping",
    "Rock Climbing",
    "Caving / Spelunking",
    "White Water Rafting",
    "Kayaking / Canoeing",
    "Surfing",
    "Scuba Diving",
    "Snorkeling",
    "Skydiving",
    "Paragliding",
    "Bungee Jumping",
    "Zip Lining",
    "Mountain Biking",
    "Wildlife Safari",
    "Skiing / Snowboarding",
]