export const countries = [
  "Select Country",
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "India",
  "Germany",
  "France",
  "Japan",
  "China",
  "Brazil",
  "South Africa",
  "Sri Lanka",
  "Mexico",
  "Russia",
  "Italy",
  "Spain",
  "Netherlands",
  "New Zealand",
  "Singapore",
  "South Korea",
  "United Arab Emirates",
  "Saudi Arabia",
  "Argentina",
  "Egypt",
  "Turkey",
  "Sweden",
  "Norway",
  "Switzerland",
  "Belgium",
  "Thailand",
  "Malaysia",
  "Vietnam",
  "Indonesia",
  "Philippines"
];
